language: node_js
node_js:
  - "12"
os:
  - linux
  - osx

script:
  - npm install

env:
  - BUILD_LEADER_ID=7
jobs:
  include:
    - stage: release
      node_js: 12
      os: linux
      after_success:
        - npm run semantic-release
