name: Create Release Branch
on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      versionName:
        description: "Name of version  (ie 5.5.0)"
        required: true
        default: 1.0.0
      versionCode:
        default: 100
        description: "Version number (50500)"
        required: true
jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create release branch
        run: git checkout -b release/v${{ github.event.inputs.versionName }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "Mohit Palyekar"
          git config user.email mohit.palyekar@creativecapsule.com
      # - name: Change version number and name
      #   run: printf 'ext.version_code = ${{ github.event.inputs.versionCode }}\next.version_name = "${{ github.event.inputs.versionName }}"\n' > app_versions.gradle

      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog

      # - name: Commit changelog and manifest files
      #   id: make-commit
      #   run: |
      #     git add CHANGELOG.md
      #     git commit --message "Prepare release ${{ github.event.inputs.versionName }}"
      #     echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Push new branch
        run: git push origin release/v${{ github.event.inputs.versionName }}
      # - name: Create pull request into master
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     token: ${{ secrets.sementic-versioning }}
      #     branch: release/v${{ github.event.inputs.versionName }}
      #     base: master
      #     title: v${{ github.event.inputs.versionName }} into master
      #     reviewers: ${{ github.event.issue.user.login }}
      #     body: |
      #       Hi!
      #       This PR was created in response workflow running.
      #       I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt
      - name: Create Pull Request for develop
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add report file
          base: develop
          title: '[Example] Add report file'
          body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: report, automated pr
