name: Finish Release
on:
  # push:
  #   branches:
  #     - master

  workflow_dispatch:
    inputs:
      versionName:
        description: "Name of the release"
        required: true
        default: 1.0.0

      message:
        default: "chore: some test message"
        description: "commit message"
        required: true

jobs:
  finishrelease:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      #bug fix in release
      # - name: Create release branch
      #   run: git checkout -b release/v${{ github.event.inputs.versionName }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "Mohit Palyekar"
          git config user.email mohit.palyekar@creativecapsule.com
      # - name: Change version number and name
      #   run: printf 'ext.version_code = ${{ github.event.inputs.versionCode }}\next.version_name = "${{ github.event.inputs.versionName }}"\n' > app_versions.gradle

      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog

        # run: echo "::set-output name=commit::$(git rev-parse HEAD)"
      # - name: Commit changelog and manifest files
      #   id: make-commit
      #   run: |
      #     git add CHANGELOG.md
      #     git commit --message "Prepare release ${{ github.event.inputs.versionName }}"
      #     echo "::set-output name=commit::$(git rev-parse HEAD)"

      # - name: Push new branch
      #   run: git push origin release/v${{ github.event.inputs.versionName }}

      #some bu fix

      - uses: actions/checkout@v2
      - name: Create Pull Request for master
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ github.event.inputs.message }}
          branch: release/v${{ github.event.inputs.versionName }}
          base: master
          title: v${{ github.event.inputs.versionName }} into master
          body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: automated pr

      - name: Create Pull Request for develop
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ github.event.inputs.message }}
          branch: release/v${{ github.event.inputs.versionName }}
          base: develop
          title: v${{ github.event.inputs.versionName }} into develop
          body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: automated pr

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
