name: start release process
on:
  push:
    branches:
      - master

jobs:
  finishrelease:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Initialize mandatory git config
        run: |
          git config user.name "Mohit Palyekar"
          git config user.email mohit.palyekar@creativecapsule.com

      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.1.jh1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
